### PR TITLE
feat: multi-byte support

### PR DESCRIPTION
**Pull request by aleclarson**
Source: https://github.com/yhirose/linenoise/blob/utf8-support/linenoise.c

This commit adds the following features:
  - UTF8 support
  - Unicode 9.0 support
  - ANSI support

### CODE REVIEW

**Comment by aleclarson** [comment]
After an hour of effort, it's ready to merge! I've tested it somewhat, but you may want to look over the code just to be sure. :)

**Comment by hoelzro** [comment]
Thanks for the contribution @aleclarson!  I'm a little hesitant to merge such a large change in from another fork, because it would be another thing to keep in sync with the upstream linenoise changes and the error handling changes I've made here.  If all you want to do is make it so that your ANSI color sequences work properly in the prompt, I think we could work in a smaller change!

**Comment by aleclarson** [comment]
@hoelzro I understand the sentiment, but the upstream linenoise had just one commit in all of 2017, so I don't see it as an issue. I'd be happy to help you if a big change is made down the line, though.

**Comment by hoelzro** [comment]
Hmm...I think Unicode support would be helpful, but I'm concerned about a potential change to linenoise that we'd need to integrate, or we'd have to back out Unicode support.  It doesn't seem like there's much activity on the linenoise repo, though...I'm going to think it over over the next day or two!

**Comment by aleclarson** [comment]
@hoelzro Sounds good! I appreciate for your careful consideration. 👍

**Comment by hoelzro** [comment]
@aleclarson Thanks for your patience and your efforts - I decided to merge this after all!  I think I'll just make sure that the different upstream we're wrapping is reflected in the documentation.

**Pull request merged**
